version: "3.7"
volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:    
  vote:
    image: davidatsains/vote:master
    build: ./vote
    ports:
      - 5001:80
    depends_on:
      - redis
    networks:
      - instavote
  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust        
  result:
    image: davidatsains/result:master
    build: ./vote
    ports:
      - 5002:4000
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image: davidatsains/worker:latest
    build: ./vote
    depends_on:  
      - redis
      - db
    networks:
      - instavote

          
  
