pipeline {
    
    agent any
    tools {
        maven 'Maven 3.8.3'
    }

    stages{
        stage('build'){
            when{
              changeset "**/worker/**"
            }
            steps{
                echo 'Compiling worker app'
                dir('worker'){
                sh 'mvn compile'
            }
          }
        }
        stage('test'){
            when{
              changeset "**/worker/**"
            }
            steps{
                echo 'Running Unit Tests on worker app'
                dir('worker'){
                sh 'mvn clean test'
                }
            }
        }
        stage('package'){
            when{
              branch 'master'
              changeset "**/worker/**"
            }
            steps{
                echo 'Packaging worker app'
               dir('worker'){
               sh 'mvn package -DskipTests'
               archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
               } 
            }
        }
    }
    
    post{
        always{
            echo 'This pipeline run is completed.'
        }
        failure{
          slackSend (channel: "learning-campaign", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success{
          slackSend (channel: "learning-campaign", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)") 
        }
    }
}
