pipeline {
    
    agent any
    tools {
        maven 'Maven 3.8.3'
    }

    stages{
        stage('build'){
            steps{
                echo 'Compiling worker app'
                dir('worker'){
                sh 'mvn compile'
            }
          }
        }
        stage('test'){
            steps{
                echo 'Running Unit Tests on worker app'
                sleep 9
            }
        }
        stage('package'){
            steps{
                echo 'Packaging worker app'
                sleep 4
            }
        }
    }
    
    post{
        always{
            echo 'This pipeline run is completed.'
        }
    }
}
